services:

  # TimescaleDB database for normalized schema
  timescaledb:
    image: timescale/timescaledb:latest-pg17
    container_name: timescaledb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=sensor_data
    ports:
      - "5432:5432"
    volumes:
      - timescale_data:/var/lib/postgresql/data
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d sensor_data" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # API
  normalizer-api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: normalizer-api
    command: uvicorn src.normalizer_api:app --host 0.0.0.0 --port 8080 --reload
    ports:
      - "8080:8080"
    depends_on:
      timescaledb:
        condition: service_healthy
    environment:
      - PYTHONUNBUFFERED=1
      - GOOGLE_APPLICATION_CREDENTIALS=/secrets/normalizer-sa.json
    volumes:
      - .:/app
      - ./docker/secrets/normalizer-sa.json:/secrets/normalizer-sa.json:ro

  # Grafana
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/etc/grafana/provisioning/dashboards/Sensor_dashboard.json
    depends_on:
      timescaledb:
        condition: service_healthy
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning


  #ngrok:
  #  image: ngrok/ngrok:latest
  #  container_name: ngrok
  #  command: http normalizer-api:8080
  #  ports:
  #    - "4040:4040"
  #  environment:
  #    - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
  #  depends_on:
  #    - normalizer-api

# Persistent volume for db
volumes:
  timescale_data:
  grafana_data:
