services:

  # TimescaleDB database for normalized schema
  timescaledb:
    image: timescale/timescaledb:latest-pg17
    container_name: timescaledb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=sensor_data
    ports:
      - "5432:5432"
    volumes:
      - timescale_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d sensor_data" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # API
  normalizer-api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    container_name: normalizer-api
    command: uvicorn src.normalizer_api:app --host 0.0.0.0 --port 8080 --reload
    ports:
      - "8080:8080"
    depends_on:
      timescaledb:
        condition: service_healthy
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app

  firestore_sync:
    build:
      context: .
      dockerfile: docker/Dockerfile.history
    container_name: history_sync
    depends_on:
      timescaledb:
        condition: service_healthy
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/secrets/normalizer-sa.json
    volumes:
      - ./docker/secrets/normalizer-sa.json:/secrets/normalizer-sa.json:ro


  # Grafana
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - timescaledb



# Persistent volume for db
volumes:
  timescale_data: