services:

  # TimescaleDB database for normalized schema
  timescaledb:
    image: timescale/timescaledb:latest-pg17
    container_name: timescaledb
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - timescale_data:/var/lib/postgresql/data
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # API
  normalizer-api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: normalizer-api
    command: uvicorn src.normalizer_api:app --host 0.0.0.0 --port 8080 --reload
    ports:
      - "8080:8080"
    depends_on:
      timescaledb:
        condition: service_healthy
    environment:
      - PYTHONUNBUFFERED=1
      - GOOGLE_APPLICATION_CREDENTIALS=/secrets/normalizer-sa.json
      - POSTGRES_URL=${POSTGRES_URL}
      - GCP_PROJECT_ID=${GCP_PROJECT_ID}
      - FIRESTORE_COLLECTIONS=${FIRESTORE_COLLECTIONS}
    volumes:
      - .:/app
      - ./docker/secrets/normalizer-sa.json:/secrets/normalizer-sa.json:ro

  # Grafana
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - GF_AUTH_ANONYMOUS_ENABLED=${GRAFANA_ANONYMOUS_ENABLED}
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/etc/grafana/provisioning/dashboards/MainDashboard.json
      - GF_SERVER_ROOT_URL=http://localhost:3000/grafana/
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    depends_on:
      timescaledb:
        condition: service_healthy
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning

# Persistent volume for db
volumes:
  timescale_data:
  grafana_data:
