apiVersion: 1

datasources:
  - name: TimescaleDB
    type: postgres
    access: proxy
    url: timescaledb:5432
    user: admin
    secureJsonData:
      password: admin
    database: sensor_data
    jsonData:
      sslmode: "disable"
      postgresVersion: 1700
      timescaledb: true
    isDefault: true
