apiVersion: 1

datasources:
  - name: TimescaleDB
    type: postgres
    access: proxy
    url: timescaledb:5432
    user: ${TIMESCALE_READONLY_USER}
    secureJsonData:
      password: ${TIMESCALE_READONLY_PASSWORD}
    jsonData:
      database: ${POSTGRES_DB}
      sslmode: "disable"
      timescaledb: true
    isDefault: true
    editable: false
